name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Local storage
  shared_preferences: ^2.1.1  

  # OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/axia.jpeg
    - assets/alza.jpeg
    - assets/premiumcar.jpeg